language: node_js
node_js:
  - "node"
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm install
  - npm install -g jspm karma-cli
  - jspm install
  - jspm dl-loader
  - echo 'Testing!'
  - npm run test
